# Generated by Django 4.2.2 on 2023-10-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsite',
            options={'ordering': ('-date_created',)},
        ),
    ]
