# Generated by Django 4.2.2 on 2023-10-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsite', '0002_alter_postsite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsite',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
