# Generated by Django 4.2.2 on 2023-10-14 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsite', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsite',
            name='image',
            field=models.ImageField(default=1, upload_to='post_image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
            preserve_default=False,
        ),
    ]
