# Generated by Django 4.2.2 on 2023-10-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsite', '0005_postsite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsite',
            name='image',
        ),
    ]
