# Generated by Django 4.2.2 on 2023-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, null=True)),
                ('categorie', models.CharField(choices=[('Développeur Web', 'Développeur Web'), ('Community Manager', 'Community Manager'), ('Développeur App', 'Développeur App'), ('Développeur UX', 'Développeur UX'), ('Chef de projet', 'Chef de projet'), ('Rédacteur SEO', 'Rédacteur SEO'), ('Coaching', 'Coaching'), ('Assistant virtuel', 'Assistant virtuel'), ('Graphiste', 'Graphiste'), ('Photographe', 'Photographe')], max_length=20, null=True)),
                ('langue', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
