# Generated by Django 4.2.2 on 2023-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='liens',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
