# Generated by Django 4.2.2 on 2023-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_resource_liens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='categorie',
            field=models.CharField(choices=[('HTML et CSS', 'HTML et CSS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO'), ('REACT', 'REACT'), ('BOOTSTRAP', 'BOOTSTRAP'), ('SQL', 'SQL'), ('PHP', 'PHP'), ('iOS', 'iOS'), ('Flutter', 'Flutter'), ('Xamarin', 'Xamarin'), ('Ionic', 'Ionic'), ('Apache Cordova', 'Apache Cordova'), ('React Native', 'React Native'), (' Android', ' Android')], max_length=20, null=True),
        ),
    ]
