# Generated by Django 4.2.2 on 2023-06-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_resource_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='categorie',
            field=models.CharField(choices=[('HTML et CSS', 'HTML et CSS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO'), ('REACT', 'REACT'), ('BOOTSTRAP', 'BOOTSTRAP'), ('SQL', 'SQL'), ('PHP', 'PHP'), ('iOS', 'iOS'), ('Flutter', 'Flutter'), ('Xamarin', 'Xamarin'), ('Ionic', 'Ionic'), ('Apache Cordova', 'Apache Cordova'), ('React Native', 'React Native'), (' Android', ' Android'), (' Analyse et suivi des performances SEO', ' Analyse et suivi des performances SEO'), (' SEO local', ' SEO local'), (' SEO technique', ' SEO technique'), (' Link building', ' Link building'), (' Rédaction SEO', ' Rédaction SEO'), (' Optimisation du contenu', ' Optimisation du contenu'), (' Recherche de mots-clés', ' Recherche de mots-clés'), (' Fondamentaux du SEO', ' Fondamentaux du SEO'), (' Link building', ' Link building'), ("Marketing d'influence", "Marketing d'influence"), (' Gestion des crises et modération des communautés', ' Gestion des crises et modération des communautés'), (' Gestion de la réputation en ligne', ' Gestion de la réputation en ligne'), (' Analyse des performances et des métriques', ' Analyse des performances et des métriques'), (' Publicité sur les réseaux sociaux', ' Publicité sur les réseaux sociaux'), (' Stratégie de communication en ligne', ' Stratégie de communication en ligne'), (' Création de contenu engageant', 'Création de contenu engageant'), (' Gestion des réseaux sociaux', '   Gestion des réseaux sociaux'), ("Coaching d'équipe", "Coaching d'équipe"), (' Coaching sportif', '   Coaching sportif'), (' Coaching en développement personnel', '   Coaching en développement personnel'), (' Coaching en gestion du temps et des priorités', '   Coaching en gestion du temps et des priorités'), (' Coaching en développement personnel', '   Coaching de carrière'), (' Coaching de leadership', '   Coaching de leadership'), (' Gestion des réseaux sociaux', '   Gestion des réseaux sociaux'), (' Coaching professionnel', '   Coaching professionnel'), (' Coaching de vie', '   Coaching de vie')], max_length=200, null=True),
        ),
    ]
