# Generated by Django 4.2.2 on 2023-09-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apropos',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
