# Generated by Django 4.2.2 on 2023-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_apropos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='apropos',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
