# Generated by Django 4.2.2 on 2023-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_addresse_alter_profile_apropos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apropos',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
