# Generated by Django 4.2.2 on 2023-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_apropos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apropos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
