# Generated by Django 4.2.2 on 2023-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_apropos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upwork',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
