# Generated by Django 4.2.2 on 2023-10-08 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_upwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatar.jpg', upload_to='Profile_Images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
