# Generated by Django 4.2.2 on 2023-10-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='technologie',
            field=models.CharField(choices=[('Web Developer', 'Web Developer'), ('Mobile App Developer', 'Mobile App Developer'), ('Graphic Designer', 'Graphic Designer'), ('Content Writer', 'Content Writer'), ('Social Media Manager', 'Social Media Manager'), ('Virtual Assistant', 'Virtual Assistant'), ('Data Analyst', 'Data Analyst'), ('SEO Specialist', 'SEO Specialist'), ('Project Manager', 'Project Manager'), ('UI/UX Designer', 'UI/UX Designer'), ('iOS Developers', 'iOS Developers')], max_length=50, null=True),
        ),
    ]
