# Generated by Django 4.2.2 on 2023-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='liens',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
