# Generated by Django 4.2.2 on 2023-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0002_alter_ressource_description_alter_ressource_liens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
