# Generated by Django 4.2.2 on 2023-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0003_alter_ressource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
