# Generated by Django 4.2.2 on 2023-10-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0006_rename_date_created_ressource_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='date_creation',
        ),
    ]
